name: Update docs/data/cache
on:
  schedule:
    - cron: '0 7 * * *'

jobs:
  build:
    name: Update
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: Build data
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
    - run: node ./index.js
    - name: Commit data
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'update: data'
